test sync image

diff --git a/.github/workflows/publish-chart.yml b/.github/workflows/publish-chart.yml
--- a/.github/workflows/publish-chart.yml
+++ b/.github/workflows/publish-chart.yml
@@ -26,6 +26,13 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+    - id: install-aws-cli
+      uses: unfor19/install-aws-cli-action@v1
+      with:
+        version: 2              
+        verbose: false            
+        arch: amd64
+    - uses: chrisdickinson/setup-yq@latest
     - name: Authenticate to AWS
       uses: aws-actions/configure-aws-credentials@v4
       with:
@@ -34,6 +41,28 @@ jobs:
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
+    - name: Sync docker image to ECR
+      run: |
+        REGISTRY=$(yq eval '.image.registry' values.yaml)
+        REPOSITORY=$(yq eval '.image.repository' values.yaml)
+        TAG=$(yq eval '.image.tag' values.yaml)
+        
+        if [[ -z "$REGISTRY" || -z "$REPOSITORY" || -z "$TAG" ]]; then
+          echo "Details not found in values.yaml"
+          exit 1
+        fi
+        
+        IMAGE="$REGISTRY/$REPOSITORY:$TAG"
+        
+        docker pull "$IMAGE"
+        
+        TARGET_IMAGE="702886132326.dkr.ecr.eu-west-1.amazonaws.com/$(basename bitnami/neo4j):$TAG"
+        docker tag "$IMAGE" "$TARGET_IMAGE"
+        
+        docker push "$TARGET_IMAGE"
+      
+        yq eval ".image.registry = \"702886132326.dkr.ecr.eu-west-1.amazonaws.com\"" -i values.yaml
+
     - name: Deploy Chart
       working-directory: bitnami/neo4j
       run: |
