try

diff --git a/.github/workflows/publish-chart.yml b/.github/workflows/publish-chart.yml
--- a/.github/workflows/publish-chart.yml
+++ b/.github/workflows/publish-chart.yml
@@ -27,12 +27,13 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v4
     - id: install-aws-cli
+      name: Install awscli
       uses: unfor19/install-aws-cli-action@v1
       with:
         version: 2     
         verbose: false            
         arch: amd64
-    - name: Install YQ
+    - name: Install yq
       uses: dcarbone/install-yq-action@v1.3.1
       with:
         version: v3
@@ -104,6 +105,7 @@ jobs:
           # Define target ECR image
           TARGET_IMAGE="702886132326.dkr.ecr.eu-west-1.amazonaws.com/$REPOSITORY:$TAG"
 
+          echo "Check if $TARGET_IMAGE exist in ecr..."
             # Check if the image already exists in ECR
           if aws ecr describe-images --repository-name "$REPOSITORY" --image-ids imageTag="$TAG" > /dev/null 2>&1; then
             echo "Image already exists in ECR: $TARGET_IMAGE"
@@ -122,25 +124,25 @@ jobs:
         yq eval ".global.image.registry = \"702886132326.dkr.ecr.eu-west-1.amazonaws.com\"" -i values.yaml
         
         
-        REGISTRY=$(yq eval '.image.registry' values.yaml)
-        REPOSITORY=$(yq eval '.image.repository' values.yaml)
-        TAG=$(yq eval '.image.tag' values.yaml)
+        # REGISTRY=$(yq eval '.image.registry' values.yaml)
+        # REPOSITORY=$(yq eval '.image.repository' values.yaml)
+        # TAG=$(yq eval '.image.tag' values.yaml)
         
-        if [[ -z "$REGISTRY" || -z "$REPOSITORY" || -z "$TAG" ]]; then
-          echo "Details not found in values.yaml"
-          exit 1
-        fi
+        # if [[ -z "$REGISTRY" || -z "$REPOSITORY" || -z "$TAG" ]]; then
+        #   echo "Details not found in values.yaml"
+        #   exit 1
+        # fi
         
-        IMAGE="$REGISTRY/$REPOSITORY:$TAG"
+        # IMAGE="$REGISTRY/$REPOSITORY:$TAG"
         
-        /usr/local/bin/docker pull "$IMAGE"
+        # /usr/local/bin/docker pull "$IMAGE"
         
-        TARGET_IMAGE="702886132326.dkr.ecr.eu-west-1.amazonaws.com/bitnami/neo4j:$TAG"
-        /usr/local/bin/docker tag "$IMAGE" "$TARGET_IMAGE"
+        # TARGET_IMAGE="702886132326.dkr.ecr.eu-west-1.amazonaws.com/bitnami/neo4j:$TAG"
+        # /usr/local/bin/docker tag "$IMAGE" "$TARGET_IMAGE"
         
-        /usr/local/bin/docker push "$TARGET_IMAGE"
+        # /usr/local/bin/docker push "$TARGET_IMAGE"
       
-        yq eval ".global.image.registry = \"702886132326.dkr.ecr.eu-west-1.amazonaws.com\"" -i values.yaml
+        # yq eval ".global.image.registry = \"702886132326.dkr.ecr.eu-west-1.amazonaws.com\"" -i values.yaml
     # - name: Sync image to ECR
     #   working-directory: bitnami/neo4j
     #   run: |
